server:
  port: 8888
  servlet:
    context-path: /webapp

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: ps
    password: ps
  application:
    name: webapp
  h2:
    console:
      enabled: true
      path: /dbconsole