server:
  port: 8888
  servlet:
    context-path: /app

spring:
  application:
    name: hibernate-app
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: postgre
    password:
